### ISSUE TITLE
sbcl and ccl complain on usage of damn-fast-stable-queue about function array

### ISSUE THREAD

**Issue by sabracrolleton** [phoe/damn-fast-priority-queue#14]
Sample code:

    (let ((q (damn-fast-stable-priority-queue:make-queue 10)))
        (damn-fast-stable-priority-queue:enqueue q :foo 1)
        (damn-fast-stable-priority-queue:dequeue q))

The warning message from sbcl:

; caught WARNING:
;   The function ARRAY is undefined, and its name is reserved by ANSI CL so that
;   even if it were defined later, the code doing so would not be portable.
; 
; compilation unit finished
;   Undefined function:
;     ARRAY
;   caught 1 WARNING condition

**Comment by phoe** [comment]
Probably from here:

https://github.com/phoe/damn-fast-priority-queue/blob/9b436de2c1dd296180c10e57e96227e5b4193ff1/damn-fast-stable-priority-queue/src.lisp#L49-L55

**Comment by sabracrolleton** [comment]
Thank you.

**Comment by phoe** [comment]
No, thank *you* - TIL that MACROLET around DEFSTRUCT initforms is 
useless because the construction macro forms seem to not be expanded by 
DEFSTRUCT.
