### ISSUE TITLE
static queue size option

### ISSUE THREAD

**Issue by mfiano** [phoe/damn-fast-priority-queue#3]
It would be a useful feature to disable adjustment when constructing a queue, and signal a condition if the queue is full when enqueuing, as it could help detect cycles in an event system before your heap is exhausted, as well as give insight into performance penalties.

**Comment by phoe** [comment]
Good idea. I'll implement that.

**Comment by phoe** [comment]
I think it would be good to implement that via extending the `extension-factor` type to `(integer 1 256)` and the extension code should signal an error of a new condition type if extension factor is set to `1` (meaning the vector length is multiplied by 1 and therefore stays the same). How does this sound?

**Comment by mfiano** [comment]
That sounds like *a* solution. I'm not sure if it is a good one yet. My concern is that the extension code would be needlessly invoked, and the code for determining if the extension code should be invoked.

**Comment by phoe** [comment]
I mean, we will still need an explicit check for `(= extension-factor 1)`. If that's the case, signal an error; otherwise, adjust the array.

**Comment by mfiano** [comment]
It does sound like a decent solution in retrospect. My only concern now is, from a user-centric API perspective, dual purposing an integral type for what a user would like a boolean option for. I assume a user in most cases would leave the extension factor to 2 as most implementations of resizable arrays use, and then they'd want a boolean option for the "staticness".

**Comment by phoe** [comment]
Sounds good. I'll add an explicit boolean override instead in form of an optional constructor parameter that defaults to `t`.

**Comment by mfiano** [comment]
I think this is a good solution. It's just that while it is mathematically correct to specify 1, it is not such a good API, and not very intuitive over something a bit more explicit. Like I said, a user is not going to be thinking about the extension factor very often, and with a dedicated option in their eldoc completion that describes controlling exactly what they want, I just think that it'd be more accessible. Maybe this is wrong for me to assume, but that's my thought :)

**Comment by phoe** [comment]
hey wait this ain't done just yet the PR isn't merged and all
