### ISSUE TITLE
Feature request: map, find

### ISSUE THREAD

**Issue by mfiano** [phoe/damn-fast-priority-queue#5]
Hello, I finally got around to using this library in an actual project. Kind of ironic considering I am the reason it got created. In this current project of mine, I need a priority queue for several different applications, most of which it suits perfectly. However, one application of use is for an event logging buffer of sorts, where events are logged by priorities, and then can be replayed later (by mapping over the queue). I therefor kindly request the ability to map over all enqueued elements of a queue. See [queues](https://github.com/oconnore/queues) for the library I was previously using to handle this, called `map-queue` there.

Additionally, it would be nice, but not immediately required, to have a `find` operation, to search for some enqueued item given some predicate.

Thanks!

**Comment by phoe** [comment]
Mapping is easily doable, I can do that. Find will be linear, though, unless you have some clever way of implementing it in a heap.

**Comment by mfiano** [comment]
I expect `find` to be linear. In any case, it is not immediately required as mapping is.

**Comment by phoe** [comment]
OK, will add these. What kind of function signatures are you looking for? `(q:map queue (lambda (x) ...))`?

I'd assume one could implement `q:find`, `q:find-if`, `q:find-if-not` just like the `cl` ones by using such a `q:map` function with a non-local return in the passed function.

**Comment by mfiano** [comment]
Yes, `(q:map queue (lambda (x) ...))`

**Comment by phoe** [comment]
Done in #6
